/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-06-28 21:04:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class actualizar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<link rel=\"icon\" href=\"./images/icono_quickshop.png\">\r\n");
      out.write("	<meta charset=\"ISO-8859-1\">\r\n");
      out.write("	<title>Actualizar Usuario</title>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"./cssssss/actualizarrr.css\">\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap\"	rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header class=\"header\">\r\n");
      out.write("		<div class=\"logo\">\r\n");
      out.write("			<img src=\"./images/definitivo black.png\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"saludo\">\r\n");
      out.write("			<h3>Bienvenido, ");
      out.print(session.getAttribute("nombre1"));
      out.write("!</h3>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"user\">\r\n");
      out.write("			<button class=\"dropbtn\">\r\n");
      out.write("				<img src=\"./images/user.png\"> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("			</button>\r\n");
      out.write("			<div class=\"dropdown-content\">\r\n");
      out.write("				<a href=\"actualizar.jsp\">Actualizar Datos</a>\r\n");
      out.write("				<a href=\"listadoPedidos.jsp\">Mis Pedidos</a>\r\n");
      out.write("				<a href=\"ServletUsuario?tipo=Salir\">Cerrar Sesión</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<main>\r\n");
      out.write("		<form action=\"ServletUsuario\" method=\"post\">\r\n");
      out.write("			<div class=\"contenido\">\r\n");
      out.write("				<h1>Actualizar mis Datos</h1>\r\n");
      out.write("				<div class=\"formulario\">\r\n");
      out.write("					<input type=\"hidden\" value=\"");
      out.print(session.getAttribute("codigo"));
      out.write("\" name=\"txtCodigoA\" readonly=\"readonly\" />\r\n");
      out.write("					<div class=\"nombres\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<p style=\"text-align: center;\">Primer Nombre</p>\r\n");
      out.write("							<input type=\"text\" value=\"");
      out.print(session.getAttribute("nombre1"));
      out.write("\"	name=\"txtNombre1A\" />\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<p style=\"text-align: center;\">Segundo Nombre</p>\r\n");
      out.write("							<input type=\"text\" value=\"");
      out.print(session.getAttribute("nombre2"));
      out.write("\"	name=\"txtNombre2A\" />\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"apellidos\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<p style=\"text-align: center;\">Primer Apellido</p>\r\n");
      out.write("							<input type=\"text\" value=\"");
      out.print(session.getAttribute("apellido1"));
      out.write("\" name=\"txtApellido1A\" />\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<p style=\"text-align: center;\">Segundo Apellido</p>\r\n");
      out.write("							<input type=\"text\" value=\"");
      out.print(session.getAttribute("apellido2"));
      out.write("\" name=\"txtApellido2A\" />\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"correo\">\r\n");
      out.write("						<p>Correo</p>\r\n");
      out.write("						<input type=\"text\" value=\"");
      out.print(session.getAttribute("correo"));
      out.write("\" name=\"txtCorreoA\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"clave\">\r\n");
      out.write("						<p>Clave</p>\r\n");
      out.write("						<input type=\"password\" value=\"");
      out.print(session.getAttribute("clave"));
      out.write("\" name=\"txtClaveA\" />\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"actualizar\">\r\n");
      out.write("					<input type=\"submit\" value=\"Actualizar\" name=\"tipo\" />\r\n");
      out.write("				</div>\r\n");
      out.write("				<p style=\"text-align: center; font-size: 13px\">\r\n");
      out.write("					Por seguridad de\r\n");
      out.write("					la cuenta se redireccionará a la pagina inicio para volver a\r\n");
      out.write("					ingresar sus credenciales\r\n");
      out.write("				</p>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"svg-back\">\r\n");
      out.write("		<a href=\"listadoProductos.jsp\" class=\"volver\">\r\n");
      out.write("			<svg width=\"81\" height=\"81\" fill=\"#2acf86\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("			          <path d=\"M22 12a10 10 0 1 0-20 0 10 10 0 0 0 20 0Zm-11.86 3.69-2.86-3a.49.49 0 0 1-.1-.15.54.54 0 0 1-.1-.16.94.94 0 0 1 0-.76 1 1 0 0 1 .21-.33l3-3a1.004 1.004 0 0 1 1.42 1.42L10.41 11H16a1 1 0 0 1 0 2h-5.66l1.25 1.31a1.001 1.001 0 0 1-1.45 1.38Z\"></path>\r\n");
      out.write("			</svg>\r\n");
      out.write("		</a>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"./javascript/actualizar.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
